# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brapp', '0002_auto_20180222_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='brapp.Review'),
        ),
    ]
