# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 00:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brapp', '0003_auto_20180222_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='book',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='brapp.Book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='review',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='brapp.Review'),
        ),
    ]
