# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 01:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brapp', '0006_auto_20180222_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='review',
            new_name='reviews',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='review',
            new_name='reviews',
        ),
    ]
