# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 04:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brapp', '0008_auto_20180222_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reviews',
        ),
        migrations.AddField(
            model_name='review',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userreviews', to='brapp.Book'),
        ),
    ]
