# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 04:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brapp', '0009_auto_20180222_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userreviews', to='brapp.User'),
        ),
    ]
